### ISSUE TITLE
Docker: Sync more than one phonebook

### ISSUE THREAD

**Issue by KingKahn123** [andig/carddav2fb#226]
Hi,

I have 4 different phonebooks in fritzbox defined. Therefore I have 4 different config files created. Is it possible to sync all 4 phonebooks with one docker container via the cron job?

**Comment by git-developer** [comment]
This is an example for a single `docker-compose.yml` with one service (container) per phonebook:
```yaml
---
services:
  carddav2fb-a:
    container_name: carddav2fb-a
    volumes:
      - ./a:/data
    image: andig/carddav2fb
    restart: unless-stopped
  carddav2fb-b:
    container_name: carddav2fb-b
    volumes:
      - ./b:/data
    image: andig/carddav2fb
    restart: unless-stopped
```
Each phonebook has its own subdirectory (`./a`, `./b`) with its own configuration. It might not be exactly what you're looking for, but it reduces the configuration overhead for multiple phonebooks.
